### ISSUE TITLE
Text box shows text is encoded after searching

### ISSUE THREAD

**Issue by shungruuw** [shungruuw/jobcado_fe#28]
<img width="684" alt="image" src="https://user-images.githubusercontent.com/100369357/165451878-4940f7ea-2b67-4e1b-84dd-89b8ab40e137.png">

Text box shows text is encoded after searching.

E.g. Searching "software engineer" becomes "software%20engineer" after searching.

**Comment by ttorogeldi** [comment]
@shungruuw  Fixed.Soon Bael deploy it
