### ISSUE TITLE
Bottom sticky search in search result page to one row

### ISSUE THREAD

**Issue by shungruuw** [shungruuw/jobcado_fe#38]
Can we change the bottom sticky search into one line like below? Thanks!

<img width="383" alt="image" src="https://user-images.githubusercontent.com/100369357/165655926-35e92c83-6e92-420a-ac5b-3530c8539b35.png">

**Comment by shungruuw** [comment]
This is for mobile.

**Comment by ttorogeldi** [comment]
Changed
