### ISSUE TITLE
Add button to search results

### ISSUE THREAD

**Issue by shungruuw** [shungruuw/jobcado_fe#45]
Can we add a button with an arrow in each organic search result in the color #B0B65D?

**Comment by ttorogeldi** [comment]
I think this applies to google adsense

**Comment by ttorogeldi** [comment]
Could you tell me exactly where, please?Thanks!

**Comment by shungruuw** [comment]
Something like this:

<img width="735" alt="image" src="https://user-images.githubusercontent.com/100369357/166883094-aaf1eaba-6332-417a-a09d-20e58b64fe55.png">

the word in the button should be "Chi tiết".

**Comment by ttorogeldi** [comment]
Yes, of course. I'll do it this weekend.

**Comment by ttorogeldi** [comment]
Done

**Comment by shungruuw** [comment]
Thanks!
