### ISSUE TITLE
Append "việc làm" to the end of the `query` parameter for ad

### ISSUE THREAD

**Issue by shungruuw** [shungruuw/jobcado_fe#46]
We are currently appending "job" to the end of the `query` parameter for the ad (in `pageOptions`). Can you replace "job" with the Vietnemese equivalent "việc làm"? Thanks!

**Comment by ttorogeldi** [comment]
Yes of course

**Comment by ttorogeldi** [comment]
@shungruuw Could you check, if it's fixed can you close?

**Comment by shungruuw** [comment]
Yes, this is fixed. thanks!
