### ISSUE TITLE
Change `pubId` value in the ad

### ISSUE THREAD

**Issue by shungruuw** [shungruuw/jobcado_fe#47]
Please change the value of `pubId` in the ad to be pub-1142122012459064. Thanks!

**Comment by ttorogeldi** [comment]
@shungruuw But that doesn't help either.

**Comment by shungruuw** [comment]
The current `pubId` value is of a test account so we need your help to replace it with our account which is pub-1142122012459064. Thanks!

**Comment by shungruuw** [comment]
Thanks!
