### ISSUE TITLE
Show location and salary in search results

### ISSUE THREAD

**Issue by shungruuw** [shungruuw/jobcado_fe#52]
Can we add the location and salary information directly in the search results?

The below information should be in the search results

<img width="370" alt="image" src="https://user-images.githubusercontent.com/100369357/166882407-edeca6e9-c51d-495a-8365-65d8db9af664.png">

**Comment by ttorogeldi** [comment]
Yes, of course. I'll do it this weekend.

**Comment by ttorogeldi** [comment]
done

**Comment by shungruuw** [comment]
Thanks! I've added another issue but it would be great if you can add more padding between the elements.
