### ISSUE TITLE
The subtitle in the home page is the browser default font and not Open Sans

### ISSUE THREAD

**Issue by shungruuw** [shungruuw/jobcado_fe#53]
The subtitle in the homepage is the browser default font and not Open Sans for some reason.

<img width="315" alt="image" src="https://user-images.githubusercontent.com/100369357/166883640-1707a97c-84b8-4e26-b8dd-d523d7de1fbb.png">

**Comment by ttorogeldi** [comment]
Fixed. Please wait for an update

**Comment by shungruuw** [comment]
Thanks!
